[package]
name = "xscreen"
version = "0.1.0"
authors = ["Bruflot <git@bruflot.com>"]
edition = "2018"

[dependencies]
image = "*"
png = "0.14.1"

[dependencies.xlib]
path = "xlib"

[profile.release]
lto = true