[package]
name = "xscreen"
version = "0.1.0"
authors = ["Bruflot <git@bruflot.com>"]
edition = "2018"

[dependencies]
image = "0.21"
png = "0.14"
clap = "2.33"
chrono = "0.4"
x11 = "*"

[dependencies.xlib]
path = "xlib"

[profile.release]
lto = true